# Generated by Django 4.0.3 on 2022-03-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('trackname', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('tempo', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('valence', models.IntegerField()),
                ('loudness', models.IntegerField()),
                ('key', models.IntegerField()),
                ('liveness', models.IntegerField()),
                ('danceability', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.IntegerField()),
                ('acousticness', models.IntegerField()),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('search_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('loudness', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('tempo_confidence', models.IntegerField()),
                ('key', models.IntegerField()),
                ('key_confidence', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('mode_confidence', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('time_signature_confidence', models.IntegerField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.track')),
            ],
        ),
    ]
